name: Run Python Project Daily at 6:00 AM IST

on:
  schedule:
    # Run every day at 6:00 AM IST (0:30 AM UTC)
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Using Ubuntu as the runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Adjust based on your Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Make sure you have a requirements.txt file

    - name: Run Python Script
      run: |
        python SymbolPredictor.py  # Replace with your script or command to run your project
